FROM php:7.0-apache
COPY nofraud/ /var/www/html/
RUN cd /etc/apache2/mods-enabled && ln -fs ../mods-available/rewrite.load rewrite.load
RUN cd /var/www/html && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN cd /var/www/html && php composer-setup.php
RUN apt update ; apt install -y git
RUN apt install zip unzip
RUN cd /var/www/html && php composer.phar install
RUN cd /var/www/html
RUN mkdir data
RUN vendor/bin/phinx migrate
