FROM php:7.0-apache
COPY nofraud/ /var/www/html/
COPY mlplugin /var/www/mlplugin
COPY nofraud-sample-data/nofraudconfig/ /var/www/html/data
COPY nofraud-sample-data/machinelearning/data /var/www/mlplugin/data
RUN cd /etc/apache2/mods-enabled && ln -fs ../mods-available/rewrite.load rewrite.load
RUN cd /var/www/html && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN cd /var/www/html && php composer-setup.php
RUN apt update ; apt install -y zip unzip git python python-pip python-dev
RUN cd /var/www/html && php composer.phar install
RUN curl https://bootstrap.pypa.io/get-pip.py > /tmp/get-pip.py ; python /tmp/get-pip.py ; pip install tensorflow
 
